// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package enforcementmock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewCheckerInterfaceMock creates a new instance of CheckerInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCheckerInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *CheckerInterfaceMock {
	mock := &CheckerInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// CheckerInterfaceMock is an autogenerated mock type for the CheckerInterface type
type CheckerInterfaceMock struct {
	mock.Mock
}

type CheckerInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *CheckerInterfaceMock) EXPECT() *CheckerInterfaceMock_Expecter {
	return &CheckerInterfaceMock_Expecter{mock: &_m.Mock}
}

// EnsureNotRevoked provides a mock function for the type CheckerInterfaceMock
func (_mock *CheckerInterfaceMock) EnsureNotRevoked(ctx context.Context, jti string) error {
	ret := _mock.Called(ctx, jti)

	if len(ret) == 0 {
		panic("no return value specified for EnsureNotRevoked")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) error); ok {
		r0 = returnFunc(ctx, jti)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// CheckerInterfaceMock_EnsureNotRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnsureNotRevoked'
type CheckerInterfaceMock_EnsureNotRevoked_Call struct {
	*mock.Call
}

// EnsureNotRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
func (_e *CheckerInterfaceMock_Expecter) EnsureNotRevoked(ctx interface{}, jti interface{}) *CheckerInterfaceMock_EnsureNotRevoked_Call {
	return &CheckerInterfaceMock_EnsureNotRevoked_Call{Call: _e.mock.On("EnsureNotRevoked", ctx, jti)}
}

func (_c *CheckerInterfaceMock_EnsureNotRevoked_Call) Run(run func(ctx context.Context, jti string)) *CheckerInterfaceMock_EnsureNotRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *CheckerInterfaceMock_EnsureNotRevoked_Call) Return(err error) *CheckerInterfaceMock_EnsureNotRevoked_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *CheckerInterfaceMock_EnsureNotRevoked_Call) RunAndReturn(run func(ctx context.Context, jti string) error) *CheckerInterfaceMock_EnsureNotRevoked_Call {
	_c.Call.Return(run)
	return _c
}
