// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package enforcementmock

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewRevokedTokenReaderInterfaceMock creates a new instance of RevokedTokenReaderInterfaceMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRevokedTokenReaderInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *RevokedTokenReaderInterfaceMock {
	mock := &RevokedTokenReaderInterfaceMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RevokedTokenReaderInterfaceMock is an autogenerated mock type for the RevokedTokenReaderInterface type
type RevokedTokenReaderInterfaceMock struct {
	mock.Mock
}

type RevokedTokenReaderInterfaceMock_Expecter struct {
	mock *mock.Mock
}

func (_m *RevokedTokenReaderInterfaceMock) EXPECT() *RevokedTokenReaderInterfaceMock_Expecter {
	return &RevokedTokenReaderInterfaceMock_Expecter{mock: &_m.Mock}
}

// IsTokenRevoked provides a mock function for the type RevokedTokenReaderInterfaceMock
func (_mock *RevokedTokenReaderInterfaceMock) IsTokenRevoked(ctx context.Context, jti string) (bool, error) {
	ret := _mock.Called(ctx, jti)

	if len(ret) == 0 {
		panic("no return value specified for IsTokenRevoked")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (bool, error)); ok {
		return returnFunc(ctx, jti)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) bool); ok {
		r0 = returnFunc(ctx, jti)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, jti)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RevokedTokenReaderInterfaceMock_IsTokenRevoked_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTokenRevoked'
type RevokedTokenReaderInterfaceMock_IsTokenRevoked_Call struct {
	*mock.Call
}

// IsTokenRevoked is a helper method to define mock.On call
//   - ctx context.Context
//   - jti string
func (_e *RevokedTokenReaderInterfaceMock_Expecter) IsTokenRevoked(ctx interface{}, jti interface{}) *RevokedTokenReaderInterfaceMock_IsTokenRevoked_Call {
	return &RevokedTokenReaderInterfaceMock_IsTokenRevoked_Call{Call: _e.mock.On("IsTokenRevoked", ctx, jti)}
}

func (_c *RevokedTokenReaderInterfaceMock_IsTokenRevoked_Call) Run(run func(ctx context.Context, jti string)) *RevokedTokenReaderInterfaceMock_IsTokenRevoked_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RevokedTokenReaderInterfaceMock_IsTokenRevoked_Call) Return(b bool, err error) *RevokedTokenReaderInterfaceMock_IsTokenRevoked_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *RevokedTokenReaderInterfaceMock_IsTokenRevoked_Call) RunAndReturn(run func(ctx context.Context, jti string) (bool, error)) *RevokedTokenReaderInterfaceMock_IsTokenRevoked_Call {
	_c.Call.Return(run)
	return _c
}
